package com.lasthopesoftware.bluewater.client.connection.session.initialization

import com.lasthopesoftware.bluewater.client.connection.libraries.ProvideLibraryConnections

interface ControlConnectionInitialization : ProvideLibraryConnections
