package com.lasthopesoftware.bluewater.client.browsing

import com.lasthopesoftware.bluewater.NavigateApplication
import com.lasthopesoftware.bluewater.client.browsing.files.access.LibraryFileProvider
import com.lasthopesoftware.bluewater.client.browsing.files.access.ProvideItemFiles
import com.lasthopesoftware.bluewater.client.browsing.files.list.FileListViewModel
import com.lasthopesoftware.bluewater.client.browsing.files.list.ReusablePlaylistFileItemViewModelProvider
import com.lasthopesoftware.bluewater.client.browsing.files.properties.ProvideLibraryFileProperties
import com.lasthopesoftware.bluewater.client.browsing.items.access.ProvideItems
import com.lasthopesoftware.bluewater.client.browsing.items.list.ItemListViewModel
import com.lasthopesoftware.bluewater.client.browsing.items.list.PlaybackLibraryItems
import com.lasthopesoftware.bluewater.client.browsing.items.list.ReusableChildItemViewModelProvider
import com.lasthopesoftware.bluewater.client.browsing.items.list.menus.changes.ItemListMenuMessage
import com.lasthopesoftware.bluewater.client.browsing.items.list.menus.changes.handlers.ItemListMenuBackPressedHandler
import com.lasthopesoftware.bluewater.client.browsing.library.access.ILibraryProvider
import com.lasthopesoftware.bluewater.client.browsing.library.access.ILibraryStorage
import com.lasthopesoftware.bluewater.client.browsing.library.access.RemoveLibraries
import com.lasthopesoftware.bluewater.client.browsing.library.access.session.CachedSelectedLibraryIdProvider
import com.lasthopesoftware.bluewater.client.browsing.library.access.session.SelectBrowserLibrary
import com.lasthopesoftware.bluewater.client.browsing.library.access.session.SelectedLibraryViewModel
import com.lasthopesoftware.bluewater.client.browsing.navigation.NavigationMessage
import com.lasthopesoftware.bluewater.client.connection.libraries.ProvideUrlKey
import com.lasthopesoftware.bluewater.client.connection.polling.PollForLibraryConnections
import com.lasthopesoftware.bluewater.client.connection.selected.ProvideSelectedConnection
import com.lasthopesoftware.bluewater.client.connection.session.ConnectionSessionManager
import com.lasthopesoftware.bluewater.client.connection.session.ConnectionWatcherViewModel
import com.lasthopesoftware.bluewater.client.playback.engine.selection.LookupSelectedPlaybackEngineType
import com.lasthopesoftware.bluewater.client.playback.nowplaying.storage.GetNowPlayingState
import com.lasthopesoftware.bluewater.client.playback.nowplaying.view.viewmodels.NowPlayingCoverArtViewModel
import com.lasthopesoftware.bluewater.client.playback.nowplaying.view.viewmodels.NowPlayingFilePropertiesViewModel
import com.lasthopesoftware.bluewater.client.playback.nowplaying.view.viewmodels.playlist.NowPlayingPlaylistViewModel
import com.lasthopesoftware.bluewater.client.playback.service.PlaybackServiceController
import com.lasthopesoftware.bluewater.client.stored.library.items.StateChangeBroadcastingStoredItemAccess
import com.lasthopesoftware.bluewater.client.stored.library.items.files.StoredFileAccess
import com.lasthopesoftware.bluewater.client.stored.sync.SyncScheduler
import com.lasthopesoftware.bluewater.permissions.read.ProvideReadPermissionsRequirements
import com.lasthopesoftware.bluewater.permissions.write.ProvideWritePermissionsRequirements
import com.lasthopesoftware.bluewater.settings.repository.access.HoldApplicationSettings
import com.lasthopesoftware.bluewater.shared.android.messages.ViewModelMessageBus
import com.lasthopesoftware.bluewater.shared.android.permissions.ManagePermissions
import com.lasthopesoftware.bluewater.shared.messages.RegisterForTypedMessages
import com.lasthopesoftware.bluewater.shared.messages.application.ScopedApplicationMessageBus
import com.lasthopesoftware.resources.strings.StringResources

interface BrowserViewDependencies {
	val selectedLibraryViewModel: SelectedLibraryViewModel
	val nowPlayingFilePropertiesViewModel: NowPlayingFilePropertiesViewModel
	val selectedLibraryIdProvider: CachedSelectedLibraryIdProvider
	val itemProvider: ProvideItems
	val messageBus: ScopedApplicationMessageBus
	val storedItemAccess: StateChangeBroadcastingStoredItemAccess
	val playbackServiceController: PlaybackServiceController
	val itemFileProvider: ProvideItemFiles
	val menuMessageBus: ViewModelMessageBus<ItemListMenuMessage>
	val itemListMenuBackPressedHandler: ItemListMenuBackPressedHandler
	val libraryFilePropertiesProvider: ProvideLibraryFileProperties
	val urlKeyProvider: ProvideUrlKey
	val stringResources: StringResources
	val libraryFilesProvider: LibraryFileProvider
	val applicationNavigation: NavigateApplication
	val libraryConnectionProvider: ConnectionSessionManager
	val storedFileAccess: StoredFileAccess
	val syncScheduler: SyncScheduler
	val libraryProvider: ILibraryProvider
	val libraryStorage: ILibraryStorage
	val libraryRemoval: RemoveLibraries
	val readPermissionsRequirements: ProvideReadPermissionsRequirements
	val writePermissionsRequirements: ProvideWritePermissionsRequirements
	val permissionsManager: ManagePermissions
	val navigationMessages: RegisterForTypedMessages<NavigationMessage>
	val applicationSettingsRepository: HoldApplicationSettings
	val selectedPlaybackEngineTypeAccess: LookupSelectedPlaybackEngineType
	val libraryBrowserSelection: SelectBrowserLibrary
	val playbackLibraryItems: PlaybackLibraryItems
	val nowPlayingState: GetNowPlayingState
	val selectedConnectionProvider: ProvideSelectedConnection
	val pollForConnections: PollForLibraryConnections
	val nowPlayingCoverArtViewModel: NowPlayingCoverArtViewModel
	val nowPlayingPlaylistViewModel: NowPlayingPlaylistViewModel
	val connectionWatcherViewModel: ConnectionWatcherViewModel
	val itemListViewModel: ItemListViewModel
	val fileListViewModel: FileListViewModel
	val reusablePlaylistFileItemViewModelProvider: ReusablePlaylistFileItemViewModelProvider
	val reusableChildItemViewModelProvider: ReusableChildItemViewModelProvider
}
