version: "3.7"

services:
  gradle:
    image: ${TAG_ID:-project_blue_build}
    build:
      context: .
    volumes:
      - gradle-home:/home/gradle
    environment:
      - ANDROID_STORE_PASSWORD=${ANDROID_STORE_PASSWORD}
      - ANDROID_KEY_STORE_PASSWORD=${ANDROID_KEY_STORE_PASSWORD}

volumes:
  gradle-home:
