package com.lasthopesoftware.bluewater.client.browsing.items.media.files.properties

object KnownFileProperties {
	/* Utility string constants */
	const val ARTIST = "Artist"
	const val ALBUM_ARTIST = "Album Artist"
	const val ALBUM = "Album"
	const val DURATION = "Duration"
	const val NAME = "Name"
	const val FILENAME = "Filename"
	const val TRACK = "Track #"
	const val NUMBER_PLAYS = "Number Plays"
	const val LAST_PLAYED = "Last Played"
	const val AUDIO_ANALYSIS_INFO = "Audio Analysis Info"
	const val GET_COVER_ART_INFO = "Get Cover Art Info"
	const val IMAGE_FILE = "Image File"
	const val KEY = "Key"
	const val STACK_FILES = "Stack Files"
	const val STACK_TOP = "Stack Top"
	const val STACK_VIEW = "Stack View"
	const val RATING = "Rating"
	const val LAST_SKIPPED = "Last Skipped"
	const val LengthInPcmBlocks = "Length In PCM Blocks"
	const val DATE_CREATED = "Date Created"
	const val DATE_IMPORTED = "Date Imported"
	const val DATE_MODIFIED = "Date Modified"
	const val DATE_TAGGED = "Date Tagged"
	const val DATE_FIRST_RATED = "Date First Rated"
	const val DATE_LAST_OPENED = "Date Last Opened"
	const val FILE_SIZE = "File Size"
	const val DATE = "Date"
	const val VolumeLevelR128 = "Volume Level (R128)"
	const val VolumeLevelReplayGain = "Volume Level (ReplayGain)"
	const val PeakGain = "replaygain_track_peak"
	const val WAVEFORM = "Waveform"
}
