package com.lasthopesoftware.bluewater.client.browsing.files.properties

object NormalizedFileProperties {
	const val Artist = "Artist"
	const val AlbumArtist = "Album Artist"
	const val Album = "Album"
	const val Band = "Band"
	const val DiscNumber = "Disc #"
	const val Name = "Name"
	const val Duration = "Duration"
	const val Filename = "Filename"
	const val Track = "Track #"
	const val NumberPlays = "Number Plays"
	const val LastPlayed = "Last Played"
	const val LastPlayedAlbum = "Last Played (album)"
	const val LastLyricsLookup = "Last Lyrics Lookup"
	const val AudioAnalysisInfo = "Audio Analysis Info"
	const val GetCoverArtInfo = "Get Cover Art Info"
	const val ImageFile = "Image File"
	const val Key = "Key"
	const val StackFiles = "Stack Files"
	const val StackTop = "Stack Top"
	const val StackView = "Stack View"
	const val Rating = "Rating"
	const val LastSkipped = "Last Skipped"
	const val LengthInPcmBlocks = "Length In PCM Blocks"
	const val DateCreated = "Date Created"
	const val DateImported = "Date Imported"
	const val DateModified = "Date Modified"
	const val DateTagged = "Date Tagged"
	const val DateFirstRated = "Date First Rated"
	const val DateLastRated = "Date Last Rated"
	const val DateLastOpened = "Date Last Opened"
	const val FileSize = "File Size"
	const val Date = "Date"
	const val VolumeLevelR128 = "Volume Level (R128)"
	const val VolumeLevelReplayGain = "Volume Level (ReplayGain)"
	const val PeakGain = "replaygain_track_peak"
	const val Waveform = "Waveform"
	const val Genre = "Genre"
	const val Lyrics = "Lyrics"
	const val Comment = "Comment"
	const val Composer = "Composer"
	const val Custom = "Custom"
	const val Publisher = "Publisher"
	const val TotalDiscs = "Total Discs"
}
