package com.lasthopesoftware.bluewater.client

import com.lasthopesoftware.bluewater.AccessApplicationState
import com.lasthopesoftware.promises.extensions.LaunchActivitiesForResults

interface ActivitySuppliedDependencies {
	val registeredActivityResultsLauncher: LaunchActivitiesForResults
	val applicationStateAccess: AccessApplicationState
}
