package com.lasthopesoftware.bluewater.client.settings

import com.lasthopesoftware.bluewater.permissions.read.ProvideReadPermissionsRequirements
import com.lasthopesoftware.bluewater.permissions.write.ProvideWritePermissionsRequirements
import com.lasthopesoftware.bluewater.shared.android.permissions.ManagePermissions

interface PermissionsDependencies {
	val readPermissionsRequirements: ProvideReadPermissionsRequirements
	val writePermissionsRequirements: ProvideWritePermissionsRequirements
	val permissionsManager: ManagePermissions
}
